### ISSUE TITLE
Linter Warning

### ISSUE THREAD

**Issue by MikeyZee** [MikeyZee/GuessIt#3]
Trimming empty <div> at line  11 col 3 (MediumDiff file) 
Trimming empty <div> at line  12 col 3 (HardDiff File) 

tried researching but not sure what it means?

**Comment by andrepearce** [comment]
Will look into it today and get back to you on it.

**Comment by imkeegs** [comment]
ill ch3ck it 0

- 
@MikeyZee 
> _**hng**_ 

ut

**Comment by andrepearce** [comment]
@MikeyZee This is a warning that is showing up simply to inform you that you have an empty <div>. Meaning it is redundant, doing nothing there so you should get rid of it. I have created a pull request  #4 addressing this. Review and merge if you are happy with it.

**Comment by MikeyZee** [comment]
Thank you very much Andre that was so dumb, hopefully I didn't take too much of your time to have a look at that.
