### ISSUE TITLE
This is a real problem now I promise 

### ISSUE THREAD

**Issue by MikeyZee** [MikeyZee/GuessIt#5]
I am trying to get the random number generator working. Currently I can get a number to be generated and displayed (which I don't want in the end) between a certain value which I define not through a variable, which would be the next step. What I am trying to do now is get the function Userguess actually working. This is the main part of the whole thing and the problem i am having is I cant define gennum in my function. I am able to define guess as it was an ID created in HTML, so i did that through document.getelementbyid which worked. The problem is I can't define gennum in my function as what I am trying to define it as is the variable gennum which i don't know how to do so I simply wrote it in which doesn't work (Line 22 and 28 of guessing.html) 

Does this make sense?

See I can simply use the code which I found on a website but I feel like that is too easy and I don't really understand it. Whereas if I write the whole thing out myself it makes sense and I feel like it will be optimised for my html layout. I used the code which I found as a reference for the number generator but that was pretty much it. 

this is the website I used 
https://stackoverflow.com/questions/5688100/how-to-create-a-number-guessing-game-in-javascript

Thankyou very much Andre

**Comment by andrepearce** [comment]
Fixed in pull requests #6 and #7
